// Generated by scripts/build-content.mjs. Do not edit by hand.
import type { Article } from "./schema";

export const articles: Article[] = [
  {
    "id": "6860206",
    "legacyPath": "/NewsDetail/6860206.html",
    "publishedAt": "2026-03-02 13:48:40",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860206",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860206.html",
        "kind": "news-detail",
        "title": "What is your supply capacity?",
        "description": "With a daily production capacity of 5,000 units, annual shipments range from 1.5 million to 2 million units.",
        "seo": {
          "title": "What is your supply capacity? | LBH APPLIANCES",
          "description": "With a daily production capacity of 5,000 units, annual shipments range from 1.5 million to 2 million units."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "With a daily production capacity of 5,000 units, annual shipments range from 1.5 million to 2 million units."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860206.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860206",
        "publishedAt": "2026-03-02 13:48:40",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860206",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860206.html",
        "kind": "news-detail",
        "title": "你们的供货能力如何？",
        "description": "日产能为 5,000 件，年出货量为 150 万至 200 万件。",
        "seo": {
          "title": "你们的供货能力如何？ | LBH APPLIANCES",
          "description": "日产能为 5,000 件，年出货量为 150 万至 200 万件。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "日产能为 5,000 件，年出货量为 150 万至 200 万件。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860206.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860206",
        "publishedAt": "2026-03-02 13:48:40",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860207",
    "legacyPath": "/NewsDetail/6860207.html",
    "publishedAt": "2026-03-02 13:49:23",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860207",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860207.html",
        "kind": "news-detail",
        "title": "What are your main products?",
        "description": "High-speed hair dryers across various market segments, all-in-one air styling tools, air-based garment care products, and personal grooming and styling tools of varying grades.",
        "seo": {
          "title": "What are your main products? | LBH APPLIANCES",
          "description": "High-speed hair dryers across various market segments, all-in-one air styling tools, air-based garment care products, and personal grooming and styling tools of varying grades."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "High-speed hair dryers across various market segments, all-in-one air styling tools, air-based garment care products, and personal grooming and styling tools of varying grades."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860207.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860207",
        "publishedAt": "2026-03-02 13:49:23",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860207",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860207.html",
        "kind": "news-detail",
        "title": "你们的主要产品有哪些？",
        "description": "涵盖不同细分市场的高速吹风机、多功能空气造型工具、空气衣物护理产品，以及不同档次的个人护理与造型工具。",
        "seo": {
          "title": "你们的主要产品有哪些？ | LBH APPLIANCES",
          "description": "涵盖不同细分市场的高速吹风机、多功能空气造型工具、空气衣物护理产品，以及不同档次的个人护理与造型工具。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "涵盖不同细分市场的高速吹风机、多功能空气造型工具、空气衣物护理产品，以及不同档次的个人护理与造型工具。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860207.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860207",
        "publishedAt": "2026-03-02 13:49:23",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860208",
    "legacyPath": "/NewsDetail/6860208.html",
    "publishedAt": "2026-03-02 13:49:40",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860208",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860208.html",
        "kind": "news-detail",
        "title": "Who are the partners?",
        "description": "Radialight, VODANA, Sinbo, LIPWEL, VINTIS, etc.",
        "seo": {
          "title": "Who are the partners? | LBH APPLIANCES",
          "description": "Radialight, VODANA, Sinbo, LIPWEL, VINTIS, etc."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Radialight, VODANA, Sinbo, LIPWEL, VINTIS, etc."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860208.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860208",
        "publishedAt": "2026-03-02 13:49:40",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860208",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860208.html",
        "kind": "news-detail",
        "title": "你们有哪些合作伙伴？",
        "description": "合作伙伴包括 Radialight、VODANA、Sinbo、LIPWEL、VINTIS 等。",
        "seo": {
          "title": "你们有哪些合作伙伴？ | LBH APPLIANCES",
          "description": "合作伙伴包括 Radialight、VODANA、Sinbo、LIPWEL、VINTIS 等。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "合作伙伴包括 Radialight、VODANA、Sinbo、LIPWEL、VINTIS 等。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860208.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860208",
        "publishedAt": "2026-03-02 13:49:40",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860209",
    "legacyPath": "/NewsDetail/6860209.html",
    "publishedAt": "2026-03-02 13:49:58",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860209",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860209.html",
        "kind": "news-detail",
        "title": "How strong are your company's R&D capabilities?",
        "description": "We possess years of experience in the R&D and commercialization of small air appliances. We hold an independent portfolio of air duct and motor technologies, backed by numerous invention and utility model patents. Furthermore, we launch four new products annually.",
        "seo": {
          "title": "How strong are your company's R&D capabilities? | LBH APPLIANCES",
          "description": "We possess years of experience in the R&D and commercialization of small air appliances. We hold an independent portfolio of air duct and motor technologies, backed by numerous invention and utility model patents. Furthermore, we launch four new products annually."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "We possess years of experience in the R&D and commercialization of small air appliances. We hold an independent portfolio of air duct and motor technologies, backed by numerous invention and utility model patents. Furthermore, we launch four new products annually."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860209.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860209",
        "publishedAt": "2026-03-02 13:49:58",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860209",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860209.html",
        "kind": "news-detail",
        "title": "你们公司的研发能力如何？",
        "description": "我们拥有多年小型空气电器研发与商业化经验，具备独立的风道和电机技术，拥有多项发明与实用新型专利，每年推出四款新产品。",
        "seo": {
          "title": "你们公司的研发能力如何？ | LBH APPLIANCES",
          "description": "我们拥有多年小型空气电器研发与商业化经验，具备独立的风道和电机技术，拥有多项发明与实用新型专利，每年推出四款新产品。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "我们拥有多年小型空气电器研发与商业化经验，具备独立的风道和电机技术，拥有多项发明与实用新型专利，每年推出四款新产品。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860209.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860209",
        "publishedAt": "2026-03-02 13:49:58",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860210",
    "legacyPath": "/NewsDetail/6860210.html",
    "publishedAt": "2026-03-02 13:50:16",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860210",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860210.html",
        "kind": "news-detail",
        "title": "What material are your products made of?",
        "description": "PP, PC, aluminum alloy, etc.",
        "seo": {
          "title": "What material are your products made of? | LBH APPLIANCES",
          "description": "PP, PC, aluminum alloy, etc."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "PP, PC, aluminum alloy, etc."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860210.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860210",
        "publishedAt": "2026-03-02 13:50:16",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860210",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860210.html",
        "kind": "news-detail",
        "title": "产品采用哪些材料？",
        "description": "材料包括 PP、PC、铝合金等。",
        "seo": {
          "title": "产品采用哪些材料？ | LBH APPLIANCES",
          "description": "材料包括 PP、PC、铝合金等。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "材料包括 PP、PC、铝合金等。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860210.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860210",
        "publishedAt": "2026-03-02 13:50:16",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860211",
    "legacyPath": "/NewsDetail/6860211.html",
    "publishedAt": "2026-03-02 13:50:33",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860211",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860211.html",
        "kind": "news-detail",
        "title": "What is your power range?",
        "description": "1300W-2000W",
        "seo": {
          "title": "What is your power range? | LBH APPLIANCES",
          "description": "1300W-2000W"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "1300W-2000W"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860211.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860211",
        "publishedAt": "2026-03-02 13:50:33",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860211",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860211.html",
        "kind": "news-detail",
        "title": "产品的功率范围是多少？",
        "description": "功率范围为 1300W-2000W。",
        "seo": {
          "title": "产品的功率范围是多少？ | LBH APPLIANCES",
          "description": "功率范围为 1300W-2000W。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "功率范围为 1300W-2000W。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860211.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860211",
        "publishedAt": "2026-03-02 13:50:33",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860212",
    "legacyPath": "/NewsDetail/6860212.html",
    "publishedAt": "2026-03-02 13:50:45",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860212",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860212.html",
        "kind": "news-detail",
        "title": "Could you send me a free sample?",
        "description": "Yes, but would you mind covering the shipping costs? If you place an order, the fee will be fully refunded.",
        "seo": {
          "title": "Could you send me a free sample? | LBH APPLIANCES",
          "description": "Yes, but would you mind covering the shipping costs? If you place an order, the fee will be fully refunded."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Yes, but would you mind covering the shipping costs? If you place an order, the fee will be fully refunded."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860212.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860212",
        "publishedAt": "2026-03-02 13:50:45",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860212",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860212.html",
        "kind": "news-detail",
        "title": "可以寄送免费样品吗？",
        "description": "可以，但需要您承担运费。如果您随后下单，这笔费用将全额退还。",
        "seo": {
          "title": "可以寄送免费样品吗？ | LBH APPLIANCES",
          "description": "可以，但需要您承担运费。如果您随后下单，这笔费用将全额退还。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以，但需要您承担运费。如果您随后下单，这笔费用将全额退还。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860212.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860212",
        "publishedAt": "2026-03-02 13:50:45",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860213",
    "legacyPath": "/NewsDetail/6860213.html",
    "publishedAt": "2026-03-02 13:51:01",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860213",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860213.html",
        "kind": "news-detail",
        "title": "What is your minimum order quantity?",
        "description": "We support a Minimum Order Quantity (MOQ) of 500 units.",
        "seo": {
          "title": "What is your minimum order quantity? | LBH APPLIANCES",
          "description": "We support a Minimum Order Quantity (MOQ) of 500 units."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "We support a Minimum Order Quantity (MOQ) of 500 units."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860213.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860213",
        "publishedAt": "2026-03-02 13:51:01",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860213",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860213.html",
        "kind": "news-detail",
        "title": "最低起订量是多少？",
        "description": "我们支持的最低起订量（MOQ）为 500 件。",
        "seo": {
          "title": "最低起订量是多少？ | LBH APPLIANCES",
          "description": "我们支持的最低起订量（MOQ）为 500 件。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "我们支持的最低起订量（MOQ）为 500 件。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860213.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860213",
        "publishedAt": "2026-03-02 13:51:01",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860214",
    "legacyPath": "/NewsDetail/6860214.html",
    "publishedAt": "2026-03-02 13:51:12",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860214",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860214.html",
        "kind": "news-detail",
        "title": "What colors can I choose?",
        "description": "We can produce any color according to your requirements. Simply provide the color number, and we will take care of the rest.",
        "seo": {
          "title": "What colors can I choose? | LBH APPLIANCES",
          "description": "We can produce any color according to your requirements. Simply provide the color number, and we will take care of the rest."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "We can produce any color according to your requirements. Simply provide the color number, and we will take care of the rest."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860214.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860214",
        "publishedAt": "2026-03-02 13:51:12",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860214",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860214.html",
        "kind": "news-detail",
        "title": "可以选择哪些颜色？",
        "description": "可以根据您的要求生产任何颜色。只需提供色号，其余工作由我们完成。",
        "seo": {
          "title": "可以选择哪些颜色？ | LBH APPLIANCES",
          "description": "可以根据您的要求生产任何颜色。只需提供色号，其余工作由我们完成。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以根据您的要求生产任何颜色。只需提供色号，其余工作由我们完成。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860214.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860214",
        "publishedAt": "2026-03-02 13:51:12",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860215",
    "legacyPath": "/NewsDetail/6860215.html",
    "publishedAt": "2026-03-02 13:51:26",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860215",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860215.html",
        "kind": "news-detail",
        "title": "Can I print my own logo?",
        "description": "Yes, provided the order quantity exceeds our Minimum Order Quantity (MOQ).",
        "seo": {
          "title": "Can I print my own logo? | LBH APPLIANCES",
          "description": "Yes, provided the order quantity exceeds our Minimum Order Quantity (MOQ)."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Yes, provided the order quantity exceeds our Minimum Order Quantity (MOQ)."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860215.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860215",
        "publishedAt": "2026-03-02 13:51:26",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860215",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860215.html",
        "kind": "news-detail",
        "title": "可以印制自己的标志吗？",
        "description": "可以，前提是订单数量超过我们的最低起订量（MOQ）。",
        "seo": {
          "title": "可以印制自己的标志吗？ | LBH APPLIANCES",
          "description": "可以，前提是订单数量超过我们的最低起订量（MOQ）。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以，前提是订单数量超过我们的最低起订量（MOQ）。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860215.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860215",
        "publishedAt": "2026-03-02 13:51:26",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860216",
    "legacyPath": "/NewsDetail/6860216.html",
    "publishedAt": "2026-03-02 13:51:39",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860216",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860216.html",
        "kind": "news-detail",
        "title": "Can I customize the outer packaging boxes?",
        "description": "Certainly. However, a Minimum Order Quantity (MOQ) applies. We can send you sample images for your confirmation.",
        "seo": {
          "title": "Can I customize the outer packaging boxes? | LBH APPLIANCES",
          "description": "Certainly. However, a Minimum Order Quantity (MOQ) applies. We can send you sample images for your confirmation."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Certainly. However, a Minimum Order Quantity (MOQ) applies. We can send you sample images for your confirmation."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860216.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860216",
        "publishedAt": "2026-03-02 13:51:39",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860216",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860216.html",
        "kind": "news-detail",
        "title": "可以定制外包装盒吗？",
        "description": "可以，但有最低起订量要求。我们可以发送样图供您确认。",
        "seo": {
          "title": "可以定制外包装盒吗？ | LBH APPLIANCES",
          "description": "可以，但有最低起订量要求。我们可以发送样图供您确认。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以，但有最低起订量要求。我们可以发送样图供您确认。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860216.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860216",
        "publishedAt": "2026-03-02 13:51:39",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860217",
    "legacyPath": "/NewsDetail/6860217.html",
    "publishedAt": "2026-03-02 13:51:54",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860217",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860217.html",
        "kind": "news-detail",
        "title": "What certificates do you have?",
        "description": "ISO 9001, FCC, CE, UL, KC, PSE, UKCA, and others—meeting the certification requirements of the vast majority of countries worldwide.",
        "seo": {
          "title": "What certificates do you have? | LBH APPLIANCES",
          "description": "ISO 9001, FCC, CE, UL, KC, PSE, UKCA, and others—meeting the certification requirements of the vast majority of countries worldwide."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "ISO 9001, FCC, CE, UL, KC, PSE, UKCA, and others—meeting the certification requirements of the vast majority of countries worldwide."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860217.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860217",
        "publishedAt": "2026-03-02 13:51:54",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860217",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860217.html",
        "kind": "news-detail",
        "title": "你们有哪些认证？",
        "description": "包括 ISO 9001、FCC、CE、UL、KC、PSE、UKCA 等，可满足全球绝大多数国家的认证要求。",
        "seo": {
          "title": "你们有哪些认证？ | LBH APPLIANCES",
          "description": "包括 ISO 9001、FCC、CE、UL、KC、PSE、UKCA 等，可满足全球绝大多数国家的认证要求。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "包括 ISO 9001、FCC、CE、UL、KC、PSE、UKCA 等，可满足全球绝大多数国家的认证要求。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860217.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860217",
        "publishedAt": "2026-03-02 13:51:54",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860218",
    "legacyPath": "/NewsDetail/6860218.html",
    "publishedAt": "2026-03-02 13:52:10",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860218",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860218.html",
        "kind": "news-detail",
        "title": "How long is your warranty period?",
        "description": "The standard shelf life is one year.",
        "seo": {
          "title": "How long is your warranty period? | LBH APPLIANCES",
          "description": "The standard shelf life is one year."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "The standard shelf life is one year."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860218.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860218",
        "publishedAt": "2026-03-02 13:52:10",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860218",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860218.html",
        "kind": "news-detail",
        "title": "保修期有多长？",
        "description": "标准期限为一年。",
        "seo": {
          "title": "保修期有多长？ | LBH APPLIANCES",
          "description": "标准期限为一年。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "标准期限为一年。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860218.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860218",
        "publishedAt": "2026-03-02 13:52:10",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860219",
    "legacyPath": "/NewsDetail/6860219.html",
    "publishedAt": "2026-03-02 13:52:21",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860219",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860219.html",
        "kind": "news-detail",
        "title": "What is the proportion of defective products?",
        "description": "The after-sales service rate is less than 5 per 1,000 units.",
        "seo": {
          "title": "What is the proportion of defective products? | LBH APPLIANCES",
          "description": "The after-sales service rate is less than 5 per 1,000 units."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "The after-sales service rate is less than 5 per 1,000 units."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860219.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860219",
        "publishedAt": "2026-03-02 13:52:21",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860219",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860219.html",
        "kind": "news-detail",
        "title": "不良品比例是多少？",
        "description": "售后率低于千分之五。",
        "seo": {
          "title": "不良品比例是多少？ | LBH APPLIANCES",
          "description": "售后率低于千分之五。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "售后率低于千分之五。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860219.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860219",
        "publishedAt": "2026-03-02 13:52:21",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860220",
    "legacyPath": "/NewsDetail/6860220.html",
    "publishedAt": "2026-03-02 13:52:35",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860220",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860220.html",
        "kind": "news-detail",
        "title": "Do your products use proprietary molds?",
        "description": "Yes, they are all proprietary-mold products that we have independently designed and developed.",
        "seo": {
          "title": "Do your products use proprietary molds? | LBH APPLIANCES",
          "description": "Yes, they are all proprietary-mold products that we have independently designed and developed."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Yes, they are all proprietary-mold products that we have independently designed and developed."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860220.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860220",
        "publishedAt": "2026-03-02 13:52:35",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860220",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860220.html",
        "kind": "news-detail",
        "title": "产品采用私模吗？",
        "description": "是的，所有产品均由我们自主设计和开发，采用独立模具。",
        "seo": {
          "title": "产品采用私模吗？ | LBH APPLIANCES",
          "description": "是的，所有产品均由我们自主设计和开发，采用独立模具。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "是的，所有产品均由我们自主设计和开发，采用独立模具。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860220.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860220",
        "publishedAt": "2026-03-02 13:52:35",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860221",
    "legacyPath": "/NewsDetail/6860221.html",
    "publishedAt": "2026-03-02 13:52:50",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860221",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860221.html",
        "kind": "news-detail",
        "title": "If I need a sample, could you make just one for me?",
        "description": "Of course, we also hope to establish a long-term partnership, so that we can reserve samples exclusively for you.",
        "seo": {
          "title": "If I need a sample, could you make just one for me? | LBH APPLIANCES",
          "description": "Of course, we also hope to establish a long-term partnership, so that we can reserve samples exclusively for you."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Of course, we also hope to establish a long-term partnership, so that we can reserve samples exclusively for you."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860221.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860221",
        "publishedAt": "2026-03-02 13:52:50",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860221",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860221.html",
        "kind": "news-detail",
        "title": "如果需要样品，可以只制作一件吗？",
        "description": "当然可以。我们也希望建立长期合作关系，以便为您专门预留样品。",
        "seo": {
          "title": "如果需要样品，可以只制作一件吗？ | LBH APPLIANCES",
          "description": "当然可以。我们也希望建立长期合作关系，以便为您专门预留样品。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "当然可以。我们也希望建立长期合作关系，以便为您专门预留样品。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860221.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860221",
        "publishedAt": "2026-03-02 13:52:50",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860222",
    "legacyPath": "/NewsDetail/6860222.html",
    "publishedAt": "2026-03-02 13:53:02",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860222",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860222.html",
        "kind": "news-detail",
        "title": "If I place a small order first, followed by a larger order, could you offer me a discount?",
        "description": "We look forward to a long-term partnership; we will offer a discount on your second order.",
        "seo": {
          "title": "If I place a small order first, followed by a larger order, could you offer me a discount? | LBH APPLIANCES",
          "description": "We look forward to a long-term partnership; we will offer a discount on your second order."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "We look forward to a long-term partnership; we will offer a discount on your second order."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860222.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860222",
        "publishedAt": "2026-03-02 13:53:02",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860222",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860222.html",
        "kind": "news-detail",
        "title": "先下小订单，再下大订单，可以优惠吗？",
        "description": "我们期待长期合作，会在您的第二次订单中提供优惠。",
        "seo": {
          "title": "先下小订单，再下大订单，可以优惠吗？ | LBH APPLIANCES",
          "description": "我们期待长期合作，会在您的第二次订单中提供优惠。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "我们期待长期合作，会在您的第二次订单中提供优惠。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860222.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860222",
        "publishedAt": "2026-03-02 13:53:02",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860223",
    "legacyPath": "/NewsDetail/6860223.html",
    "publishedAt": "2026-03-02 13:53:13",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860223",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860223.html",
        "kind": "news-detail",
        "title": "What is the difference between a traditional hair dryer and a high-speed hair dryer?",
        "description": "The primary differences between traditional hair dryers and high-speed hair dryers lie in their motors, airflow speed, temperature, and additional features. High-speed hair dryers typically utilize brushless motors, offering faster rotational speeds and higher airflow velocities; moreover, they often incorporate hair-care functions—such as negative ion technology—to protect the hair. In contrast, traditional hair dryers predominantly employ carbon-brush motors, which generate lower airflow speeds and are more prone to causing hair damage.",
        "seo": {
          "title": "What is the difference between a traditional hair dryer and a high-speed hair dryer? | LBH APPLIANCES",
          "description": "The primary differences between traditional hair dryers and high-speed hair dryers lie in their motors, airflow speed, temperature, and additional features. High-speed hair dryers typically utilize brushless motors, offering faster rotational speeds and higher airflow velocities; moreover, they often incorporate hair-care functions—such as negative ion technology—to protect the hair. In contrast, traditional hair dryers predominantly employ carbon-brush motors, which generate lower airflow speeds and are more prone to causing hair damage."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "The primary differences between traditional hair dryers and high-speed hair dryers lie in their motors, airflow speed, temperature, and additional features. High-speed hair dryers typically utilize brushless motors, offering faster rotational speeds and higher airflow velocities; moreover, they often incorporate hair-care functions—such as negative ion technology—to protect the hair. In contrast, traditional hair dryers predominantly employ carbon-brush motors, which generate lower airflow speeds and are more prone to causing hair damage."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860223.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860223",
        "publishedAt": "2026-03-02 13:53:13",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860223",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860223.html",
        "kind": "news-detail",
        "title": "传统吹风机与高速吹风机有什么区别？",
        "description": "主要区别在于电机、风速、温度和附加功能。高速吹风机通常采用无刷电机，转速和风速更高，并常配备负离子等护发功能。传统吹风机多采用碳刷电机，风速较低，也更容易造成头发损伤。",
        "seo": {
          "title": "传统吹风机与高速吹风机有什么区别？ | LBH APPLIANCES",
          "description": "主要区别在于电机、风速、温度和附加功能。高速吹风机通常采用无刷电机，转速和风速更高，并常配备负离子等护发功能。传统吹风机多采用碳刷电机，风速较低，也更容易造成头发损伤。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "主要区别在于电机、风速、温度和附加功能。高速吹风机通常采用无刷电机，转速和风速更高，并常配备负离子等护发功能。传统吹风机多采用碳刷电机，风速较低，也更容易造成头发损伤。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860223.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860223",
        "publishedAt": "2026-03-02 13:53:13",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860224",
    "legacyPath": "/NewsDetail/6860224.html",
    "publishedAt": "2026-03-02 13:53:30",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860224",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860224.html",
        "kind": "news-detail",
        "title": "Is the shipping cost high?",
        "description": "Shipping rates are constantly fluctuating. However, we have 5–6 freight forwarders to choose from, so we can screen and select the best option for you.",
        "seo": {
          "title": "Is the shipping cost high? | LBH APPLIANCES",
          "description": "Shipping rates are constantly fluctuating. However, we have 5–6 freight forwarders to choose from, so we can screen and select the best option for you."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Shipping rates are constantly fluctuating. However, we have 5–6 freight forwarders to choose from, so we can screen and select the best option for you."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860224.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860224",
        "publishedAt": "2026-03-02 13:53:30",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860224",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860224.html",
        "kind": "news-detail",
        "title": "运费高吗？",
        "description": "运费会持续波动。我们有 5–6 家货运代理可供选择，可以为您筛选合适的方案。",
        "seo": {
          "title": "运费高吗？ | LBH APPLIANCES",
          "description": "运费会持续波动。我们有 5–6 家货运代理可供选择，可以为您筛选合适的方案。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "运费会持续波动。我们有 5–6 家货运代理可供选择，可以为您筛选合适的方案。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860224.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860224",
        "publishedAt": "2026-03-02 13:53:30",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860225",
    "legacyPath": "/NewsDetail/6860225.html",
    "publishedAt": "2026-03-02 13:53:42",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860225",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860225.html",
        "kind": "news-detail",
        "title": "I have other quotes that are even lower.",
        "description": "We can try to match your target rate. However, a lower price implies lower quality—and I’m sure neither of us would want to see that happen.",
        "seo": {
          "title": "I have other quotes that are even lower. | LBH APPLIANCES",
          "description": "We can try to match your target rate. However, a lower price implies lower quality—and I’m sure neither of us would want to see that happen."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "We can try to match your target rate. However, a lower price implies lower quality—and I’m sure neither of us would want to see that happen."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860225.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860225",
        "publishedAt": "2026-03-02 13:53:42",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860225",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860225.html",
        "kind": "news-detail",
        "title": "我收到过更低的报价。",
        "description": "我们可以尝试匹配您的目标价格，但更低的价格可能意味着更低的质量，这并非双方所期待的结果。",
        "seo": {
          "title": "我收到过更低的报价。 | LBH APPLIANCES",
          "description": "我们可以尝试匹配您的目标价格，但更低的价格可能意味着更低的质量，这并非双方所期待的结果。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "我们可以尝试匹配您的目标价格，但更低的价格可能意味着更低的质量，这并非双方所期待的结果。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860225.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860225",
        "publishedAt": "2026-03-02 13:53:42",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860226",
    "legacyPath": "/NewsDetail/6860226.html",
    "publishedAt": "2026-03-02 13:54:09",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860226",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860226.html",
        "kind": "news-detail",
        "title": "Can I ship via FedEx?",
        "description": "Yes, we have more cost-saving options available.",
        "seo": {
          "title": "Can I ship via FedEx? | LBH APPLIANCES",
          "description": "Yes, we have more cost-saving options available."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Yes, we have more cost-saving options available."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860226.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860226",
        "publishedAt": "2026-03-02 13:54:09",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860226",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860226.html",
        "kind": "news-detail",
        "title": "可以通过 FedEx 发货吗？",
        "description": "可以，我们也有更节省成本的选项。",
        "seo": {
          "title": "可以通过 FedEx 发货吗？ | LBH APPLIANCES",
          "description": "可以，我们也有更节省成本的选项。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以，我们也有更节省成本的选项。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860226.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860226",
        "publishedAt": "2026-03-02 13:54:09",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860227",
    "legacyPath": "/NewsDetail/6860227.html",
    "publishedAt": "2026-03-02 13:54:23",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860227",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860227.html",
        "kind": "news-detail",
        "title": "Which mode of transportation do you use?",
        "description": "Via sea or air freight. We have contracts with numerous freight forwarders and express service providers.",
        "seo": {
          "title": "Which mode of transportation do you use? | LBH APPLIANCES",
          "description": "Via sea or air freight. We have contracts with numerous freight forwarders and express service providers."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Via sea or air freight. We have contracts with numerous freight forwarders and express service providers."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860227.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860227",
        "publishedAt": "2026-03-02 13:54:23",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860227",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860227.html",
        "kind": "news-detail",
        "title": "采用哪些运输方式？",
        "description": "可以海运或空运。我们与多家货运代理和快递服务商有合作协议。",
        "seo": {
          "title": "采用哪些运输方式？ | LBH APPLIANCES",
          "description": "可以海运或空运。我们与多家货运代理和快递服务商有合作协议。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "可以海运或空运。我们与多家货运代理和快递服务商有合作协议。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860227.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860227",
        "publishedAt": "2026-03-02 13:54:23",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860228",
    "legacyPath": "/NewsDetail/6860228.html",
    "publishedAt": "2026-03-02 13:54:38",
    "author": "LBH APPLIANCES",
    "category": "faq",
    "locales": {
      "en": {
        "id": "6860228",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860228.html",
        "kind": "news-detail",
        "title": "What is your standard delivery lead time?",
        "description": "Our standard lead time is approximately 30–35 business days after receipt of the deposit; however, depending on raw material availability, the shipping cycle for certain models and colors may be as short as 25 days or less.",
        "seo": {
          "title": "What is your standard delivery lead time? | LBH APPLIANCES",
          "description": "Our standard lead time is approximately 30–35 business days after receipt of the deposit; however, depending on raw material availability, the shipping cycle for certain models and colors may be as short as 25 days or less."
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Our standard lead time is approximately 30–35 business days after receipt of the deposit; however, depending on raw material availability, the shipping cycle for certain models and colors may be as short as 25 days or less."
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860228.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "full"
        },
        "articleId": "6860228",
        "publishedAt": "2026-03-02 13:54:38",
        "author": "LBH APPLIANCES",
        "category": "faq"
      },
      "cn": {
        "id": "6860228",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860228.html",
        "kind": "news-detail",
        "title": "标准交货周期是多久？",
        "description": "收到定金后，标准交期约为 30–35 个工作日。根据原料供应情况，部分型号和颜色的发货周期可缩短至 25 天或更少。",
        "seo": {
          "title": "标准交货周期是多久？ | LBH APPLIANCES",
          "description": "收到定金后，标准交期约为 30–35 个工作日。根据原料供应情况，部分型号和颜色的发货周期可缩短至 25 天或更少。"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "收到定金后，标准交期约为 30–35 个工作日。根据原料供应情况，部分型号和颜色的发货周期可缩短至 25 天或更少。"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860228.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "full"
        },
        "articleId": "6860228",
        "publishedAt": "2026-03-02 13:54:38",
        "author": "LBH APPLIANCES",
        "category": "faq"
      }
    }
  },
  {
    "id": "6860201",
    "legacyPath": "/NewsDetail/6860201.html",
    "publishedAt": "2026-01-27 18:07:46",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860201",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860201.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860201.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860201",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860201",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860201.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860201.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860201",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860200",
    "legacyPath": "/NewsDetail/6860200.html",
    "publishedAt": "2026-01-27 18:07:40",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860200",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860200.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860200.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860200",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860200",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860200.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860200.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860200",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860199",
    "legacyPath": "/NewsDetail/6860199.html",
    "publishedAt": "2026-01-27 18:07:40",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860199",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860199.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860199.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860199",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860199",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860199.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860199.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860199",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860197",
    "legacyPath": "/NewsDetail/6860197.html",
    "publishedAt": "2026-01-27 18:07:36",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860197",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860197.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860197.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860197",
        "publishedAt": "2026-01-27 18:07:36",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860197",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860197.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860197.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860197",
        "publishedAt": "2026-01-27 18:07:36",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860196",
    "legacyPath": "/NewsDetail/6860196.html",
    "publishedAt": "2026-01-27 18:07:31",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860196",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860196.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860196.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860196",
        "publishedAt": "2026-01-27 18:07:31",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860196",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860196.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860196.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860196",
        "publishedAt": "2026-01-27 18:07:31",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860195",
    "legacyPath": "/NewsDetail/6860195.html",
    "publishedAt": "2026-01-27 18:06:45",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860195",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860195.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860195.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860195",
        "publishedAt": "2026-01-27 18:06:45",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860195",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860195.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860195.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860195",
        "publishedAt": "2026-01-27 18:06:45",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860198",
    "legacyPath": "/NewsDetail/6860198.html",
    "publishedAt": "2026-01-27 18:07:40",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860198",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860198.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860198.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860198",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860198",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860198.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860198.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860198",
        "publishedAt": "2026-01-27 18:07:40",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860205",
    "legacyPath": "/NewsDetail/6860205.html",
    "publishedAt": "2026-01-27 18:07:46",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860205",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860205.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860205.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860205",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860205",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860205.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860205.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860205",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860202",
    "legacyPath": "/NewsDetail/6860202.html",
    "publishedAt": "2026-01-27 18:07:46",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860202",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860202.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860202.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860202",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860202",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860202.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860202.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860202",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860203",
    "legacyPath": "/NewsDetail/6860203.html",
    "publishedAt": "2026-01-27 18:07:46",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860203",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860203.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860203.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860203",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860203",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860203.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860203.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860203",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  },
  {
    "id": "6860204",
    "legacyPath": "/NewsDetail/6860204.html",
    "publishedAt": "2026-01-27 18:07:46",
    "author": "LBH APPLIANCES",
    "category": "news",
    "locales": {
      "en": {
        "id": "6860204",
        "locale": "en",
        "legacyPath": "/NewsDetail/6860204.html",
        "kind": "news-detail",
        "title": "Title",
        "description": "Content introduction",
        "seo": {
          "title": "Title | LBH APPLIANCES",
          "description": "Content introduction"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "Content introduction"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860204.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "none",
          "coverage": "source-placeholder"
        },
        "articleId": "6860204",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      },
      "cn": {
        "id": "6860204",
        "locale": "cn",
        "legacyPath": "/NewsDetail/6860204.html",
        "kind": "news-detail",
        "title": "标题",
        "description": "内容介绍",
        "seo": {
          "title": "标题 | LBH APPLIANCES",
          "description": "内容介绍"
        },
        "blocks": [
          {
            "type": "rich-text",
            "paragraphs": [
              "内容介绍"
            ]
          }
        ],
        "images": [],
        "provenance": {
          "sourceUrl": "https://lbhappliances.com/en/NewsDetail/6860204.html",
          "sourceLocale": "en",
          "languageVerified": false,
          "translation": "authored",
          "coverage": "source-placeholder"
        },
        "articleId": "6860204",
        "publishedAt": "2026-01-27 18:07:46",
        "author": "LBH APPLIANCES",
        "category": "news"
      }
    }
  }
];
